### ISSUE TITLE
change in meaning in a METADATA_BLOCK reference

### ISSUE THREAD

**Issue by dericed** [privatezero/flac_markdown#22]
In the markdown is the line
> METADATA_BLOCK Zero or more metadata blocks

but the original format.html places an asterik after METADATA_BLOCK. I'm unclear as to the semantic difference here, but I think that there is one.

**Comment by retokromer** [comment]
I’m also unclear for now, but it should become clearer when the full specification is test-implemented.

**Comment by dericed** [comment]
may be worthwhile to ask for clarity on flac-dev

**Comment by retokromer** [comment]
Are you on `flac-dev`?

**Comment by JeromeMartinez** [comment]
My understanding is that `*` means "any" and `+` means "1 or more", and the info in the right column is repetition / making it more explicit. There is no other `*` so difficult to make a guess but this is the case for all other `+`.

BTW, for METADATA_BLOCK lines (the 2 lines), I would change it to "METADATA_BLOCK+" with indication in the description part that the first METADATA_BLOCK must be of BLOCK_TYPE STREAMINFO

**Comment by dericed** [comment]
This is resolved in https://github.com/privatezero/flac_markdown/commit/8a68eef10aee01b28d63f9f6e6e63a44ecfb869b and supported by https://github.com/privatezero/flac_markdown/commit/5a6e7bc9994d9f8223be1a4bf646c5a7a4ab87de.
