### ISSUE TITLE
logic mismatch

### ISSUE THREAD

**Issue by dericed** [privatezero/flac_markdown#23]
To my reading, this [section](https://github.com/privatezero/flac_markdown/blob/master/flac.md#metadata_block_data) (a list of block types separated by 'or's which is labelled with an obligation) doesn't match the original format.html. Here is appears that the phrase `The block data must match the block type in the block header. ` only relates to the last item in the list when that doesn't read that way in the original. Needs some adjustment so that both read the same way.

**Comment by privatezero** [comment]
good point, it does read that way. Do you think it would make sense to move it to the top of that section without a bullet? Or perhaps move it to its own line at the bottom withe  a 'Note: ..."

**Comment by dericed** [comment]
Fixed in https://github.com/privatezero/flac_markdown/commit/f2d61671309950e9fe9460b2d195a7789dcb774f
