### ISSUE TITLE
link to `pucrunch` compression is deed

### ISSUE THREAD

**Issue by retokromer** [privatezero/flac_markdown#27]
It’s currently at line 91.

Perhaps [this](http://a1bert.kapsi.fi/Dev/pucrunch/) is the intended document?

**Comment by dericed** [comment]
Here's the wayback machine version of the original link http://web.archive.org/web/20140827133312/http://www.cs.tut.fi/~albert/Dev/pucrunch/packing.html

**Comment by retokromer** [comment]
Thanks! «My» link is possibly the «second part».
