### ISSUE TITLE
fix semantics in frame_footer section

### ISSUE THREAD

**Issue by dericed** [privatezero/flac_markdown#3]
In the html version of the specification the FRAME_FOOTER and SUBFRAME are on the same level, see https://xiph.org/flac/format.html#frame_footer. But in the markdown, the FRAME_FOOTER section, https://github.com/privatezero/flac_markdown/blob/master/flac.md#frame_footer, contains a list of SUBFRAME components that aren't in the HTML.

Also in the HTML the phrase "The SUBFRAME_HEADER specifies which one." refers to a list of 4 types of subframe contents, but in the markdown that phrase just aspects next to the first of the 4 lists types of subframe, so the relationship between "The SUBFRAME_HEADER specifies which one." and the list of what is specified is lost.

**Comment by privatezero** [comment]
resolved in https://github.com/privatezero/flac_markdown/issues/7
