### ISSUE TITLE
describe method for expressing hex and binary data

### ISSUE THREAD

**Issue by dericed** [privatezero/flac_markdown#33]
I suggest documenting/acknowledgement a method for expressing binary and hex values. Currently the context can be inferred in most places (in not all) by understanding the number of bits described, but I think having expressions such as `0b0000` or `0x0000` would be more clear, rather than `0000` which is ambitiguous (does it mean binary, hex, decimal, etc?).

**Comment by bumblebritches57** [comment]
I've made this change in my branch called Fixed-binary-representation

**Comment by retokromer** [comment]
Caveat: it’s https://github.com/privatezero/flac_markdown/pull/38.

**Comment by retokromer** [comment]
Resolved in https://github.com/privatezero/flac_markdown/pull/38.
