### ISSUE TITLE
RICE coding

### ISSUE THREAD

**Issue by bumblebritches57** [privatezero/flac_markdown#36]
Can we stop calling it Rice coding, because people naturally think you mean unary coding, instead of exponential-golomb coding which is what you actually use.

**Comment by retokromer** [comment]
Also I would capitalise the name: `exponential-Golomb`.

**Comment by dericed** [comment]
started clarifying the coding here https://github.com/privatezero/flac_markdown/pull/37

**Comment by retokromer** [comment]
Resolved in https://github.com/privatezero/flac_markdown/pull/39.
