### ISSUE TITLE
RICE2_PARTITION list is broken in markdown

### ISSUE THREAD

**Issue by dericed** [privatezero/flac_markdown#4]
In HTML the RICE2_PARTITION has a list of two values, `5(+5)` and `?` and their meanings. In the markdown, https://github.com/privatezero/flac_markdown/blob/master/flac.md#rice2_partition, the `?` value is not present but the meaning is there.

**Comment by privatezero** [comment]
resolved in https://github.com/privatezero/flac_markdown/issues/7
