### ISSUE TITLE
mark 00 release and upload to data tracker

### ISSUE THREAD

**Issue by dericed** [privatezero/flac_markdown#47]
IMHO the rendered output of this repo should be in the cellar wg document tracker. I suggest marking a `00` release (see these for instance https://github.com/Matroska-Org/ebml-specification/releases) and then uploading draft-xiph-cellar-flac-00.xml to https://datatracker.ietf.org/submit/.

**Comment by retokromer** [comment]
As soon as it represents the «original», and the conversion to RFC text works well, yes.

**Comment by privatezero** [comment]
@dericed As recent merges seem to build ok, I will make a release later today and email related list servs!

**Comment by privatezero** [comment]
00 release established with https://github.com/privatezero/flac_markdown/releases

Link to data tracker is https://datatracker.ietf.org/doc/draft-xiph-cellar-flac/
