### ISSUE TITLE
broken list in the RESIDUAL section

### ISSUE THREAD

**Issue by dericed** [privatezero/flac_markdown#5]
In the HTML in the RESIDUAL section, there's one value in a table that is `RESIDUAL_CODING_METHOD_PARTITIONED_RICE || RESIDUAL_CODING_METHOD_PARTITIONED_RICE2` (this or that) but in the markdown, at https://github.com/privatezero/flac_markdown/blob/master/flac.md#residual, the components of the list are divided into two separate bullet points which changes the meaning.

**Comment by privatezero** [comment]
resolved in https://github.com/privatezero/flac_markdown/issues/7
