### ISSUE TITLE
broken list in FRAME_HEADER

### ISSUE THREAD

**Issue by dericed** [privatezero/flac_markdown#6]
In the markdown by the phrase `<3> Sample size in bits:` the subsequent list is supposed to be a lower depth, but the subsequent list is at the same level in the markdown.

**Comment by dericed** [comment]
note that the section of FRAME_HEADER by `if(variable blocksize) ` is also broken. The `<?>` is missing again so it's unclear what is defined here (maybe all `<?>` were lost in translation here). There is an if/else here but the if and else are at different levels.

**Comment by privatezero** [comment]
Resolved in https://github.com/privatezero/flac_markdown/issues/7
