### ISSUE TITLE
[v02] number of residuals

### ISSUE THREAD

**Issue by retokromer** [privatezero/flac_markdown#68]
In my opinion, the current section [encoded residuals](https://github.com/privatezero/flac_markdown/blob/master/flac.md#encoded-residual) is less clear than Federico Miyara’s explanation on page 383 of his _Software-Based Acoustical Measurements_ (Springer 2017):

![fullsizerender](https://user-images.githubusercontent.com/3246607/27992011-a148e7ac-6489-11e7-8231-5bb0b8ee4620.jpg)

**Comment by bumblebritches57** [comment]
The RICE/RICE2 partition stuff is easy to understand IMO, what's confusing is exactly how the RICE/Golomb/whatever-you-wanna-call-it actually works, there's like 4000 different formats for that coding system, how exactly does FLACs work?

**Comment by retokromer** [comment]
If I am the only one who would wish to see a clearer description, then I will close the issue. Sorry, English is my eleventh tongue…

Regarding the actual encodings, I am personally less concerned by their theoretical number, than by the ones currently used in the wild. So far, I have found three of them.

**Comment by bumblebritches57** [comment]
I was just going over unary/rice/expgolomb coding on wiki and there's like 5 formats I saw.

Straight unary, truncated golomb, a signed variant, and some really fucking weird version without any leading bits at all that was confusing as shit.

So yeah i have no clue how it works, i'll probs go over the libFLAC source tommorrow and try figuring out exactly how it's done again.

**Comment by retokromer** [comment]
In my opinion, the libFLAC is quite clear, but not all the files that I have found in the wild seems to be coded that way. Perhaps this could also be the subject for a lightning talk in Vienna? Anyway, I guess, at some point, I have to re-delve into my 1990s teachings!

**Comment by bumblebritches57** [comment]
Lighting talk in Vienna? what's that?

I was poking around in the source the other day and came across a few functions, `FLAC__bitwriter_golomb_bits_signed` and `FLAC__bitwriter_golomb_bits_unsigned`, and tbh they're a real mess IMO, the variable names are cryptic, the main function call in there `FLAC__bitmath_ilog2`chain calls an additional 2 functions, all to look up in an inline table to figure out the number of bits are necessary to store a certain number, when really all that's needed is `ceil(log2(abs(X)+1))`, it's extremely convoluted in my opinion; that said I've only tested my solution with unsigned numbers.

**Comment by retokromer** [comment]
I am sorry, I did presume that you already know the [No Time to Wait! Open Media, Open Formats, Open Archives](https://mediaarea.net/MediaConch/notimetowait2.html) symposium on 9–10 November in Vienna, Austria.

**Comment by retokromer** [comment]
> I was born in the 90s

I did presume in 1957 ;-)

Regarding your comment, indeed, the code can be improved in many many many points! For sure the compression can be improved a little and the speed quite a lot.

Is there any chance that you will attend the party in Vienna?

**Comment by bumblebritches57** [comment]
Unfortunately, there's a 0% chance I'll be able to, that's 4500 miles away.

tbh reverse engineering the RICE format would be easier than reading the code.

**Comment by retokromer** [comment]
>Unfortunately, there's a 0% chance I'll be able to, that's 4500 miles away.

I should be in new Orleans for the AMIA conference on 29 November – 2 December.

>tbh reverse engineering the RICE format would be easier than reading the code.

Ha! I have rewritten from scratch for a test implementation.

**Comment by bumblebritches57** [comment]
> Ha! I have rewritten from scratch for a test implementation.

Hey, so have I!!! It's not close to done, it pretty much just parses currently (well, once I get my bit reader/writer done, which I've recently started rewriting to handle different byte and bit orders, but that's another story)

**Comment by retokromer** [comment]
It’s the best way to understand it!

**Comment by retokromer** [comment]
for reference: [ModernFLAC](https://github.com/MarcusJohnson91/ModernFLAC)

**Comment by MarcusJohnson91** [comment]
ModernFLAC as well as ModernPNG and LibPCM have been merged into OVIA.
