### ISSUE TITLE
units

### ISSUE THREAD

**Issue by retokromer** [privatezero/flac_markdown#9]
Currently there is a mix between numbers and units having and not having a space in between (e.g. `48KHz` and `16 bit`). I suggest to standardise with an espace, which is easier to read. If you agree, I’m happy to go through the document and change when needed.

**Comment by dericed** [comment]
+1 for `number unit`
-1 for `numberunit`

**Comment by retokromer** [comment]
Resolved in https://github.com/privatezero/flac_markdown/pull/10.
